config/routes.rb
Vulcan::Application.routes.draw do
  resources :user_sessions, only: [:new, :create, :destroy]

  resources :projects do
    resources :tickets
  end

  root to: 'projects#index'
end

app/models/project.rb
class Project
  include DataMapper::Resource
  # implements #to_partial_path
  include ActiveModel::Conversion

  property :id,         Serial
  property :title,      String
  property :created_at, DateTime
  property :updated_at, DateTime

  has n, :tickets

  def open_tickets
    tickets.all(status: 'open')
  end

  def closed_tickets
    tickets.all(status: 'closed')
  end
end

app/models/ticket.rb
class Ticket
  include DataMapper::Resource
  # implements #to_partial_path
  include ActiveModel::Conversion

  STATUSES = %w[open closed]

  property :id,         Serial
  property :title,      String,  required: true
  property :status,     String,  required: true, default: 'open'
  property :user_id,    Integer, required: true
  property :created_at, DateTime
  property :updated_at, DateTime

  belongs_to :project

  validates_within :status, set: STATUSES

  def self.last_updated_since(date)
    all(:updated_at.gt => date, :order => [:updated_at.desc])
  end

  def self.closed
    all(status: 'closed', :order => [:updated_at.desc])
  end
end

app/models/ticket_observer.rb
require_relative './ticket'

class TicketObserver

  include DataMapper::Observer

  observe Ticket

  before :valid? do
    self.user_id ||= User.current.id
  end
end

app/models/user.rb
class User
  include DataMapper::Resource
  include ActiveModel::SecurePassword

  property :id,              Serial
  property :username,        String,     required: true, unique: true
  property :email,           String
  property :password_digest, BCryptHash, required: true

  attr_writer :password_confirmation

  has_secure_password

  has n, :tickets

  def self.current
    Thread.current[:user]
  end

  def self.current=(user)
    Thread.current[:user] = user
  end

  def tickets_in_date_range(start_date, end_date)
    tickets.all(status: 'closed', :updated_at.gte => start_date, :updated_at.lt => end_date)
  end
end

app/controllers/application_controller.rb
require 'dm-rails/middleware/identity_map'
class ApplicationController < ActionController::Base
  use Rails::DataMapper::Middleware::IdentityMap
  protect_from_forgery

  helper_method :all_projects

  before_filter :set_current_user
  helper_method :current_user
  helper_method :user_signed_in?

  private

  def all_projects
    ProjectPresenter.wrap(Project)
  end

  def set_current_user
    User.current = current_user
  end

  def current_user
    @current_user ||= User.get(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    ! current_user.nil?
  end

  def authenticate_user!
    unless user_signed_in?
      session[:request_url] = request.url
      flash[:warning] = 'You must sign in to access that page.'
      redirect_to new_user_session_url
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_user!

  rescue_from DataMapper::ObjectNotFoundError, with: :not_found

  def index
    @recent_closed_tickets = (Ticket.last_updated_since(Date.today - 1.week) & Ticket.closed).group_by { |t| t.updated_at.to_date }
  end

  def show
    @project = Project.get!(params[:id])
    @tickets = params[:closed_tickets] ? @project.closed_tickets : @project.open_tickets
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new((params[:project] || {}).slice(:title))

    if @project.save
      flash[:success] = 'Saved project.'
      redirect_to project_url(@project)
    else
      flash.now[:error] = 'Unable to save project.'
      render :new
    end
  end

  private

  def not_found
    flash[:error] = 'Unable to find project, please try again.'
    redirect_to projects_url
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  before_filter :authenticate_user!, :find_project

  def new
    @ticket = @project.tickets.new
  end

  def create
    @ticket = @project.tickets.new((params[:ticket] || {}).slice(:title))

    if @ticket.save
      flash[:success] = 'Saved ticket.'
      redirect_to project_url(@project)
    else
      flash.now[:error] = 'Unable to save ticket.'
      render :new
    end
  end

  def update
    @ticket = @project.tickets.get!(params[:id])

    if @ticket.update((params[:ticket] || {}).slice(:status))
      flash[:success] = "#{params[:ticket][:status] == 'closed' ? 'Closed' : 'Reopened'} ticket."
    else
      flash[:error] = "Unable to update ticket: #{@ticket.errors.full_messages.join(', ')}."
    end
    redirect_to project_url(@project)
  end

  private

  def find_project
    @project = Project.get!(params[:project_id])
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def new
    if @user = User.first(password_digest: cookies['digest'])
      session[:user_id] = @user.id
      flash[:success] = "Welcome back #{@user.username}!"
      redirect_to (session[:request_url] || root_url)
    else
      @user = User.new
    end
  end

  def create
    user = User.first(username: params[:user][:username])
    
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      if params[:remember_me] == "1"
        cookies["digest"] = { value: user.password_digest,
                              expires: Time.now + 4.weeks }
      else
        cookies["digest"] = nil
      end
      flash[:success] = 'Signed in.'
      redirect_to (session[:request_url] || root_url)
      session.delete :request_url
    else
      @user = User.new
      flash.now[:error] = 'Username or password did not match, please try again.'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    cookies["digest"] = nil
    flash[:success] = "Logged out!"
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def friendly_time(time)
    if time.to_date == Date.today
      time.strftime('%l:%M%P')
    else
      time.strftime('%b %-d')
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper

  # Returns the project title and open ticket count (if any).
  def project_summary(project)
    summary = sanitize(project.title)
    summary.tap do |s|
      count = project.open_tickets.count
      s << (' '.html_safe + content_tag(:span, count, class: 'badge')) if count > 0
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vulcan</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render 'shared/main_menu' %>
    <%= render 'shared/alert' %>
    <%= yield %>
  </div>
</body>
</html>

app/views/projects/_form.html.erb
<div class="row">
  <div class="span5">
    <%= simple_form_for @project do |f| %>
      <%= f.input :title, input_html: { class: 'span5' } %>
      <div class="form-actions">
        <%= f.button :submit, 'Save', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/_project.html.erb
<div class="project">
  <div class="title"><%= link_to project_summary(project), project_path(project) %></div>
</div>

app/views/projects/index.html.erb
<div class="row">
  <div class="span3">
    <%= render all_projects.alphabetized %>
  </div>

  <div class="span3 offset2">
    <% @recent_closed_tickets.each do |date, tickets| %>
      <h4><%= date.to_date.to_s(:long) %></h4>
      <%= render partial: 'tickets/short_ticket', collection: tickets %>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="page-header">
  <h2>Add project</h2>
</div>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="page-header">
  <h2 class="title"><%= @project.title %> <small><%= params[:closed_tickets] ? 'closed tickets' : 'open tickets' %></h2>

  <% if params[:closed_tickets] %>
    <%= link_to 'show open tickets', project_path(@project) %>
  <% else %>
    <%= link_to 'show closed tickets', project_path(@project, closed_tickets: true) %>
  <% end %>
</div>

<% if @tickets.count == 0 %>
  <h3>No tickets</h3>
<% else %>
  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th></th>
        <th>Updated</th>
      </tr>
    </thead>
    <tbody>
      <%= render @tickets %>
    </tbody>
  </table>
<% end %>

app/views/shared/_alert.html.erb
<% if flash.empty? %>
  <div id="alert" class="alert alert-placeholder">&nbsp;</div>
<% else %>
  <% primary_key = [:error, :warning, :success, :info].detect { |k| !flash[k].nil? } %>
  <div id="alert" class="alert alert-<%= primary_key %>"><%= flash[primary_key] %></div>
<% end %>

app/views/shared/_main_menu.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to 'Vulcan', root_path, class: 'brand' %>
      <ul class="nav">
        <li class="dropdown">
          <%= link_to 'Projects <b class="caret"></b>'.html_safe, '#', class: 'dropdown-toggle', :'data-toggle' => 'dropdown' %>
          <ul class="dropdown-menu">
            <% all_projects.alphabetized.each do |project| %>
              <li><%= link_to project_summary(project), project_path(project) %></li>
            <% end %>
          </ul>
        </li>
        <li><%= link_to 'Add project', new_project_path %></li>
        <% if @project.try(:id) %>
          <li><%= link_to 'Add ticket', new_project_ticket_path(@project) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tickets/_form.html.erb
<div class="row">
  <div class="span5">
    <%= simple_form_for [@project, @ticket] do |f| %>
      <%= f.input :title, input_html: { class: 'span5' }  %>
      <div class="form-actions">
        <%= f.button :submit, 'Save', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/tickets/_short_ticket.html.erb
<div class="closed-ticket">
  <i class="icon-ok"></i> <span class="title"><%= short_ticket.title %></span> <span class="muted"><%= short_ticket.project.title %></span>
</div>

app/views/tickets/_ticket.html.erb
<tr class="ticket">
  <td class="title"><%= ticket.title %></td>
  <td>
    <% if ticket.status == 'open' %>
      <%= link_to '<i class="icon-ok icon-white"></i> Close'.html_safe, { controller: 'tickets', action: 'update', project_id: @project.id, id: ticket.id, ticket: { status: 'closed' } }, method: :put, class: 'btn btn-success' %>
    <% else %>
      <%= link_to 'Reopen', { controller: 'tickets', action: 'update', project_id: @project.id, id: ticket.id, ticket: { status: 'open' } }, method: :put, class: 'btn btn-warning' %>
    <% end %>
  </td>
  <td><%= friendly_time ticket.updated_at %></td>
</tr>

app/views/tickets/new.html.erb
<div class="page-header">
  <h2>Add ticket to <%= @project.title %></h2>
</div>
<%= render 'form' %>

app/views/user_notifications/latest_closed_tickets.text.erb
<% @tickets.each do |ticket| %>
  <%= ticket.title %>
<% end %>

app/views/user_sessions/_sign_in_form.html.erb
<%= simple_form_for @user, url: user_sessions_path do |f| %>
  <%= f.input :username, required: false, autofocus: true %>
  <%= f.input :password %>
  <%= check_box_tag 'remember_me' %> Remember me
  <div class="form-actions">
    <%= f.submit "Sign in", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<div class="page-header">
  <h2>Sign in</h2>
</div>

<div class="row">
  <div class="span5">
    <%= render 'sign_in_form' %>
    <p>
      <%= mail_to "radiology@northwestern.edu", "request an account" %>
    </p>
  </div>
</div>